[build]
publish = ".output/public"
command = "npx pnpm i && pnpm --filter stream-markdown-parser build && pnpm --filter markstream-vue build && npm run build"

[build.environment]
NPM_FLAGS = "--version"
NODE_VERSION = "22"
