# Cloudflare Pages 配置
# https://developers.cloudflare.com/pages/functions/wrangler-configuration/

name = "markstream-playground-nuxt"
compatibility_date = "2024-01-01"

# 构建配置
command = "cd .. && npx pnpm i && pnpm --filter stream-markdown-parser build && pnpm run build && cd playground-nuxt && npm run build"
cwd = "."
pages_build_output_dir = ".output/public"

# 环境变量
[vars]
NPM_FLAGS = "--version"
NODE_VERSION = "22"
