# Cloudflare Pages 配置
# https://developers.cloudflare.com/pages/functions/wrangler-configuration/

name = "markstream-playground-react"
compatibility_date = "2024-01-01"

# 构建配置
command = "npx pnpm i && pnpm --filter stream-markdown-parser build && pnpm --filter markstream-react build && npm run build"
cwd = "."
pages_build_output_dir = "dist"

# 环境变量
[vars]
NPM_FLAGS = "--version"
NODE_VERSION = "22"
